---
driver:
  name: vagrant
  transport:
    name: winrm


provisioner:
  name: chef_solo

platforms:
# ths is 300 MB
  - name: WindowsNano
    driver_config:
      box: mwrock/WindowsNano
      box_url: https://atlas.hashicorp.com/mwrock/WindowsNano
      communicator: winrm
      vm_hostname: false
    transport:
      name: winrm
      port: 55985
      username: vagrant
      password: vagrant
      endpoint_template: "http://127.0.0.1:55985/wsman"

# this is 3.3GB
# https://vagrantcloud.com/mwrock/boxes/Windows2012R2
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2
      box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
      communicator: winrm
      vm_hostname: false
    transport:
      name: winrm

suites:
  - name: base
    provisioner:
      name: chef_solo
      run_list:
      - role[base]



